import type {
  PersistentState,
  Plan,
  Server,
  TelegramUserProfile,
  UserProfile,
} from './types'

const createProfile = (telegramUser?: TelegramUserProfile): UserProfile => ({
  id: telegramUser ? `tg_${telegramUser.id}` : 'user_local',
  firstName: telegramUser?.first_name ?? 'کاربر',
  username: telegramUser?.username ?? 'user',
  avatarUrl: telegramUser?.photo_url,
  city: 'Tehran',
  preferredRegion: 'Germany',
  walletCredit: 0,
  referralCode: `LIAN-${Math.random().toString(36).slice(2, 8).toUpperCase()}`,
  referrals: 0,
  premium: Boolean(telegramUser?.is_premium),
  memberSince: new Date().toISOString(),
})

const plans: Plan[] = [
  {
    id: 'starter-30',
    name: 'Starter 30',
    category: 'starter',
    subtitle: 'ورودی ارزان‌قیمت',
    description: 'مناسب برای پیام‌رسانی، شبکه‌های اجتماعی و یک دستگاه شخصی.',
    badge: 'بهترین ورودی',
    featured: true,
    price: 189000,
    durationDays: 30,
    deviceLimit: 2,
    locations: ['Germany', 'Turkey', 'Netherlands', 'Finland'],
    speedTier: 'Fast',
    dataCap: 'Unlimited',
    protocols: ['VLESS', 'Reality'],
    accent: 'lime',
    perks: ['تحویل فوری', 'تمدید خودکار', 'کپی یک‌کلیکی کانفیگ'],
  },
  {
    id: 'stream-90',
    name: 'Stream 90',
    category: 'streaming',
    subtitle: 'مسیرهای پایدار استریم',
    description: 'لیتنسی متعادل و مسیرهای رسانه‌ای پایدار برای تلویزیون و موبایل.',
    badge: 'محبوب',
    featured: true,
    price: 489000,
    durationDays: 90,
    deviceLimit: 4,
    locations: ['Germany', 'France', 'UK', 'Netherlands', 'UAE'],
    speedTier: 'Turbo',
    dataCap: 'Unlimited',
    protocols: ['VLESS', 'Hysteria'],
    accent: 'ice',
    perks: ['مسیر بهینه استریم', 'روتینگ اولویت‌دار', 'راهنمای نصب'],
  },
  {
    id: 'family-180',
    name: 'Family 180',
    category: 'family',
    subtitle: 'پک خانگی برای چند دستگاه',
    description: 'یک اشتراک برای خانه با اسلات کافی برای همه دستگاه‌ها.',
    badge: 'خانوادگی',
    price: 899000,
    durationDays: 180,
    deviceLimit: 8,
    locations: ['Germany', 'Turkey', 'UAE', 'Netherlands', 'Finland'],
    speedTier: 'Turbo+',
    dataCap: 'Unlimited',
    protocols: ['Reality', 'Hysteria'],
    accent: 'amber',
    perks: ['۸ دستگاه', 'اشتراک‌گذاری خانوادگی', 'صف VIP'],
  },
  {
    id: 'unlimited-365',
    name: 'Unlimited 365',
    category: 'unlimited',
    subtitle: 'بهترین ارزش بلندمدت',
    description: 'پلن سالانه تمام‌سرعت با پشتیبانی ویژه و فیلواور هوشمند.',
    badge: 'ارزش‌آفرین',
    featured: true,
    price: 1499000,
    durationDays: 365,
    deviceLimit: 10,
    locations: ['Germany', 'France', 'Sweden', 'Turkey', 'UAE', 'Netherlands'],
    speedTier: 'Flagship',
    dataCap: 'Unlimited',
    protocols: ['Reality', 'Hysteria', 'TUIC'],
    accent: 'lime',
    perks: ['صرفه‌جویی سالانه', 'پشتیبانی اولویت‌دار', 'چرخش بهترین مسیر'],
  },
  {
    id: 'business-30',
    name: 'Team Shield',
    category: 'business',
    subtitle: 'دسترسی مشترک برای تیم‌های کوچک',
    description: 'اسلات‌های مدیریت‌پذیر، پوشش گسترده دستگاه، و سرعت پیش‌بینی‌پذیر.',
    badge: 'تیمی',
    price: 749000,
    durationDays: 30,
    deviceLimit: 12,
    locations: ['Germany', 'Netherlands', 'France', 'Turkey'],
    speedTier: 'Business',
    dataCap: 'Unlimited',
    protocols: ['Reality', 'TUIC'],
    accent: 'ice',
    perks: ['۱۲ صندلی', 'صورتحساب مشترک', 'صادرکردن کانفیگ دسته‌جمعی'],
  },
]

const servers: Server[] = [
  {
    id: 'srv_001',
    city: 'Frankfurt',
    country: 'Germany',
    latency: 38,
    load: 46,
    status: 'online',
    protocols: ['Reality', 'Hysteria'],
  },
  {
    id: 'srv_002',
    city: 'Amsterdam',
    country: 'Netherlands',
    latency: 44,
    load: 53,
    status: 'online',
    protocols: ['VLESS', 'Reality'],
  },
  {
    id: 'srv_003',
    city: 'Istanbul',
    country: 'Turkey',
    latency: 61,
    load: 79,
    status: 'busy',
    protocols: ['VLESS'],
  },
  {
    id: 'srv_004',
    city: 'Dubai',
    country: 'UAE',
    latency: 69,
    load: 41,
    status: 'online',
    protocols: ['Reality', 'TUIC'],
  },
  {
    id: 'srv_005',
    city: 'Helsinki',
    country: 'Finland',
    latency: 52,
    load: 14,
    status: 'maintenance',
    protocols: ['Hysteria'],
  },
]

export const createInitialState = (
  telegramUser?: TelegramUserProfile,
): PersistentState => ({
  profile: createProfile(telegramUser),
  plans,
  services: [],
  orders: [],
  tickets: [],
  servers,
  campaigns: [
    {
      id: 'cmp_001',
      title: 'اولین سفارش',
      description: 'تخفیف مستقیم روی اولین سفارش پرداخت‌شده.',
      code: 'SAFE20',
      discountPercent: 20,
      reward: '۲۰٪ تخفیف',
      active: true,
    },
    {
      id: 'cmp_002',
      title: 'هفته تمدید',
      description: 'تخفیف اضافه اگر سرویس فعالتان نزدیک انقضا باشد.',
      code: 'RENEW10',
      discountPercent: 10,
      reward: '۱۰٪ تخفیف',
      active: true,
    },
  ],
  notices: [],
  faqs: [
    {
      id: 'faq_001',
      question: 'بعد از پرداخت چطور کانفیگ را دریافت کنم؟',
      answer: 'به محض تأیید سفارش، کانفیگ به بخش سرویس‌های من اضافه و قابل کپی یا دانلود می‌شود.',
    },
    {
      id: 'faq_002',
      question: 'آیا می‌توانم بعد از خرید مسیر خود را تغییر دهم؟',
      answer: 'بله. صفحه سرویس امکان ریست کانفیگ را دارد و پشتیبانی می‌تواند شما را به مسیر بهتری منتقل کند.',
    },
    {
      id: 'faq_003',
      question: 'آیا از آیفون، اندروید، ویندوز و مک پشتیبانی می‌کنید؟',
      answer: 'بله. راهنمای نصب سریع هر پلتفرم در بخش پشتیبانی موجود است.',
    },
    {
      id: 'faq_004',
      question: 'بعد از اتمام اشتراک چه اتفاقی می‌افتد؟',
      answer: 'وضعیت سرویس به منقضی‌شده تغییر می‌کند اما تاریخچه سفارش‌ها باقی می‌ماند و با یک ضربه می‌توانید تمدید کنید.',
    },
    {
      id: 'faq_005',
      question: 'آیا می‌توانم پلن خانوادگی را به اشتراک بگذارم؟',
      answer: 'پلن‌های خانوادگی برای چند دستگاه و استفاده مشترک طراحی شده‌اند، اما سقف دستگاه مشخصی دارند.',
    },
  ],
  customers: [],
  trialUsed: false,
})
